
//QUI DENTRO CI ANDRANNO INSERITE TUTTE LE PATH DELLE "PAGINE"
//è IL PATH CHE VEDETE QUANDO CAMBIATE PAGINA(NELL'URL)
export const RouteConstants = {
  HOME: "home",
  ANAGRAFICA: "anagrafica"
};


